# Generated by Django 5.0.7 on 2025-07-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='shop_name',
            field=models.CharField(max_length=100),
        ),
    ]
